@base = http://127.0.0.1:5077

### Konfigurerte datakilder (ingen tokenverdier)
GET {{base}}/api/config

### Komplett resultat med QR og OperationOutcome
POST {{base}}/api/populate
Content-Type: application/json

< ./examples/populate-request.json

### Ren QuestionnaireResponse
POST {{base}}/api/questionnaire-response
Content-Type: application/json

< ./examples/populate-request.json

### Syntetisk Patient
GET {{base}}/demo/fhir/Patient/demo-patient
Accept: application/fhir+json

### DHG Test: eksempelskjema (ingen eksterne oppslag)
GET {{base}}/api/examples/dhg

### DHG Test: preutfyll fra dokumentert syntetisk testperson
# Dette gjør fire POST-søk mot den konfigurerte DHG-testkilden.
POST {{base}}/api/populate
Content-Type: application/json

< ./examples/populate-request-dhg.json

### Flere lokale endepunkter med én sentral Patient
POST {{base}}/api/populate
Content-Type: application/json

< ./examples/populate-request-multi-source.json

### Endepunkter velges fra Questionnaire-URL og versjon (ingen profileId)
POST {{base}}/api/populate
Content-Type: application/json

< ./examples/populate-request-questionnaire.json
